Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "controller"
  config.disksize.size = '50GB'
  config.vm.provider "virtualbox" do |vb|
  	vb.memory = 5100
	vb.cpus = 4
	vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end
  config.vm.network :private_network, ip: "172.16.2.25"
end